evoe/api/urls.py
from django.urls import path

from evoe.api import views

api_urls = [
    path('api/v1/criar_tarefa/', views.CriarTarefa.as_view(), name='criar_tarefa'),
    path('api/v1/setar_status/', views.SetarStatus.as_view(), name='setar_status'),
]

evoe/urls.py
from django.contrib import admin
from django.urls import path, include

from evoe.api.urls import api_urls as api_v1_urls
from evoe.core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', views.index, name='index'),
    path('tarefas/', views.todo_list, name='todo_list'),
    path('gerar_token/', views.gerar_token, name='gerar_token'),
    path('atualizar_tarefa/<pk>/<acao>/', views.atualizar_tarefa, name='atualizar_tarefa'),
    path('login/', views.Login.as_view(), name='login'),
    path('register/', views.Register.as_view(), name='register'),
]

urlpatterns += api_v1_urls

evoe/api/models.py
from django.db import models

# Create your models here.

evoe/core/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models

from evoe.core import choices
from evoe.core.managers import BaseQuerySet


class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    criado_em = models.DateTimeField('criado em', auto_now_add=True)
    atualizado_em = models.DateTimeField('última atualização', auto_now=True)
    ativo = models.BooleanField(default=True)

    objects = BaseQuerySet().as_manager()

    class Meta:
        abstract = True


class Lista(BaseModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tarefas')
    titulo = models.CharField('Título da tarefa', max_length=100)
    descricao = models.TextField('Descrição da tarefa')
    status = models.CharField('Status da tarefa', max_length=50, choices=choices.OPCORES_TAREFA, default=choices.TAREFA_TODO)

evoe/api/views.py
from rest_framework import status
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from evoe.core.services import TarefaService


class CriarTarefa(APIView):
    """
        Endpoint para criar a tarefa
        Exemplo Json do post:
        {
            "titulo":"Lavar a roupa",
            "descricao":"pegar o monte de roupas sujas e por na maquina de lavar"
        }
        resultado json com id da tarefa e status 200 ok ou 400 com exception
    """

    permission_classes = (IsAuthenticated,)

    def post(self, request):
        try:
            user = request.user
            titulo = request.data.get('titulo')
            descricao = request.data.get('descricao')
            tarefa = TarefaService().criar_nova_tarefa(titulo, descricao, user)
            resultado = {
                'id_tarefa': tarefa.id.hex
            }
            return Response(resultado, status=status.HTTP_200_OK)
        except Exception as e:
            return Response(str(e), status=status.HTTP_400_BAD_REQUEST)


class ExecutarTarefa(APIView):
    """
        Endpoint para setar a tarefa como em execução
        Exemplo Json do post:
        {
            "id":"uuid_tarefa",
        }
        resultado status 200 ok ou 400 com exception
    """

    permission_classes = (IsAuthenticated,)

    def post(self, request):
        try:
            user = request.user
            tarefa_id = request.data.get('id')
            TarefaService().executar_tarefa(tarefa_id, user)
            return Response(status=status.HTTP_200_OK)
        except Exception as e:
            return Response(str(e), status=status.HTTP_400_BAD_REQUEST)


class SetarStatus(APIView):
    """
        Endpoint para setar a tarefa como concluída
        Exemplo Json do post:
        {
            "id":"uuid_tarefa",
            "status": "DOING"
        }
        opções de statu: 'TODO', 'DOING' e 'DONE
        resultado status 200 ok ou 400 com exception
    """

    permission_classes = (IsAuthenticated,)

    def post(self, request):
        try:
            user = request.user
            tarefa_id = request.data.get('id')
            status_tarefa = request.data.get('status')
            TarefaService().alterar_status(tarefa_id, user, status_tarefa)
            return Response(status=status.HTTP_200_OK)
        except Exception as e:
            return Response(str(e), status=status.HTTP_400_BAD_REQUEST)

evoe/core/views.py
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views import View
from rest_framework.authtoken.models import Token

from evoe.core import choices
from evoe.core.models import Lista
from evoe.core.services import TarefaService


def index(request):
    if not request.user.is_authenticated:
        return redirect('login')
    return redirect('todo_list')


@login_required()
def atualizar_tarefa(request, pk, acao):
    TarefaService().alterar_status(pk, request.user, acao)
    return redirect('todo_list')


@login_required()
def todo_list(request):
    lista = Lista.objects.ativos().por_usuario(request.user)
    ctx = {
        'tarefas_pendentes': lista.filter(status=choices.TAREFA_TODO),
        'tarefas_andamento': lista.filter(status=choices.TAREFA_DOING),
        'tarefas_concluidas': lista.filter(status=choices.TAREFA_DONE),
    }
    return render(request, 'core/index.html', ctx)


@login_required()
def gerar_token(request):
    obj, _ = Token.objects.get_or_create(user=request.user)
    key = obj.key
    ctx = {
        'token': key
    }
    return render(request, 'core/token.html', ctx)


def autenticar(request, usuario, senha):
    user = authenticate(request, username=usuario, password=senha)
    if user is not None:
        login(request, user)
        return redirect('index')
    else:
        messages.error(request, 'Dados inválidos')
        return render(request, 'user/login.html')


class Login(View):
    def get(self, request):
        return render(request, 'user/login.html')

    def post(self, request):
        if not request.user.is_authenticated:
            usuario = request.POST.get('user')
            senha = request.POST.get('pass')
            return autenticar(request, usuario, senha)


class Register(View):
    def get(self, request):
        return render(request, 'user/register.html')

    def post(self, request):
        if not request.user.is_authenticated:
            usuario = request.POST.get('user')
            senha = request.POST.get('pass')
            User.objects.create_user(username=usuario, password=senha)
            return autenticar(request, usuario, senha)

evoe/templates/alert_messages.html
{% if messages %}
    <div id="messages">
        {% for message in messages %}
            <div class="alert {% if message.tags %} {{ message.tags }} {% endif %} alert-dismissible fade show text-center margin-bottom-1x">
                <span class="alert-close" data-dismiss="alert"></span><i class="icon-alert-triangle"></i>&nbsp;&nbsp;
                {% if 'safe' in message.tags %}
                    {{ message|safe }}
                {% else %}
                    {{ message }}
                {% endif %}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </div>
{% endif %}

evoe/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>todo list</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <style>
        .painel {
            background: #fff;
            border-radius: 5px;
            padding: 1em;
            box-shadow: 0 .125rem .25rem rgba(0, 0, 0, .075);
        }

        .painel:hover {
            box-shadow: 0 .5rem 1rem rgba(0, 0, 0, .15) !important;
        }

        code{
            border: 1px solid #efefef;
            background: #fefefe;
            border-radius: 5px;
            padding: 3px 1rem;
        }
    </style>
</head>
<body>
{% include 'partials/header.html' %}
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
</body>
</html>

evoe/templates/core/index.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        <h1 class="my-5">Minha lista de tarefas</h1>
        <div class="row ">
            <div class="col-md-4">
                <div class="bg-light p-3 rounded">
                    <h3 class="text-center">A fazer</h3>
                    {% for tarefa in tarefas_pendentes %}
                        {% include 'partials/tarefa_mini_snippet.html' %}
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4">
                <div class="bg-light p-3 rounded">
                    <h3 class="text-center">Fazendo</h3>
                    {% for tarefa in tarefas_andamento %}
                        {% include 'partials/tarefa_mini_snippet.html' %}
                    {% endfor %}
                </div>
            </div>
            <div class="col-md-4">
                <div class="bg-light p-3 rounded">
                    <h3 class="text-center">Concluídas</h3>
                    {% for tarefa in tarefas_concluidas %}
                        {% include 'partials/tarefa_mini_snippet.html' %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

evoe/templates/core/token.html
{% extends 'base.html' %}
{% block content %}

    <div class="container">
        <h1 class="my-5">Token de acesso à API</h1>
        <div class="bg-light rounded p-3 border">
            {{ token }}
        </div>
        <p class="my-4">
            Endpoints: <br> <br>
            <code>{{ request.scheme }}://{{ request.META.HTTP_HOST }}/api/v1/criar_tarefa/</code>
            <br> <br>
            <code>{{ request.scheme }}://{{ request.META.HTTP_HOST }}/api/v1/setar_status/</code>
        </p>
        <p class="mt-4">
            <a href="{% url 'index' %}" class="btn btn-link">Voltar</a>
        </p>
    </div>

{% endblock %}

evoe/templates/partials/header.html
<header class="container">
    <div class="text-right">
        Olá {{ request.user }}.
        <br>
        <a href="{% url 'gerar_token' %}">obter token</a>
    </div>
</header>

evoe/templates/partials/tarefa_mini_snippet.html
<div class="painel mb-3">
    <h3>{{ tarefa.titulo }}</h3>
    <p>
        {{ tarefa.descricao|safe }}
    </p>
    <div class="text-center">
        {% if tarefa.status == 'TODO' %}
            <a href="{% url 'atualizar_tarefa' tarefa.pk 'DOING' %}">Executar</a>
        {% endif %}
        {% if tarefa.status == 'DOING' %}
            <a href="{% url 'atualizar_tarefa' tarefa.pk 'TODO' %}">Voltar</a>
            <a href="{% url 'atualizar_tarefa' tarefa.pk 'DONE' %}">Concluir</a>
        {% endif %}
    </div>
</div>

evoe/templates/user/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <dov class="row justify-content-center">
            <form class="col-md-5 my-5" method="post">
                {% csrf_token %}
                <div class="bg-white rounded border p-3 my-5">
                    <label for="id_user">Usuário</label>
                    <input type="text" name="user" class="form-control form-control-sm mb-3" id="id_user">
                    <label for="id_pass">Senha</label>
                    <input type="password" name="pass" class="form-control form-control-sm mb-3" id="id_pass">
                    {% include 'alert_messages.html' %}
                    <div class="row justify-content-between mt-5">
                        <a href="{% url 'register' %}" class=" col-5 btn btn-outline-secondary btn-lg mx-3">Cadastrar</a>
                        <button type="submit" class="col-5 btn btn-lg btn-primary mx-3">Login</button>
                    </div>
                </div>
            </form>
        </dov>
    </div>
{% endblock %}

evoe/templates/user/register.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <dov class="row justify-content-center">
            <form class="col-md-5 my-5" method="post">
                {% csrf_token %}
                <div class="bg-white rounded border p-3 my-5">
                    <label for="id_user">Usuário</label>
                    <input type="text" name="user" class="form-control form-control-sm mb-3" id="id_user">
                    <label for="id_pass">Senha</label>
                    <input type="password" name="pass" class="form-control form-control-sm mb-3" id="id_pass">
                    {% include 'alert_messages.html' %}
                    <div class="text-center mt-5">
                        <button type="submit" class="col-5 btn btn-lg btn-primary mx-3">Registrar</button>
                    </div>
                </div>
            </form>
        </dov>
    </div>
{% endblock %}